spring.application.name=AILearning

# DataSource
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/ai_learning_db
spring.datasource.username=postgres
spring.datasource.password=Shubham@123

    spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

logging.level.org.springframework.security=DEBUG
#jwt.secret=${JWT_SECRET}
jwt.secret=VGhpcy1pcy1hLXN1cGVyLXNlY3JldC1rZXktZm9yLWp3dC1hdXRo
gemini.api.key=AIzaSyDb6sieSrGfYRyblYhTMxHFLy1KNcreds0
spring.jackson.parser.allow-unquoted-control-chars=true
