spring.application.name=AILearning

# DataSource
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/ai_learning_db
spring.datasource.username=postgres
spring.datasource.password=Shubham@123

    spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web.reactive.function.client=DEBUG
logging.level.reactor.netty=DEBUG

#jwt.secret=${JWT_SECRET}
jwt.secret=VGhpcy1pcy1hLXN1cGVyLXNlY3JldC1rZXktZm9yLWp3dC1hdXRo
gemini.api-key=AQ.Ab8RN6KpXXi7x_OuW_MNWtibJ9vsQ8sjftzWEF291W65uNLH8Q
gemini.model=gemini-2.5-flash
spring.jackson.parser.allow-unquoted-control-chars=true